### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by djKooks** [jorgegil96/All-NBA#115]
Hi!
How do you think about use travis-ci for continuous integration of this project?
It'll be helpful for make it stable.

**Comment by jorgegil96** [comment]
Don't know much about travis-ci but any kind of testing would be great. This project is seriously lacking in that department :/
Do you have any experience with travis-ci? Could you elaborate on the benefits it brings and how complicated it is to get setup and running?  

I'll look into it anyway, thanks for the suggestion!

**Comment by djKooks** [comment]
@jorgegil96 Okay. Than I'll put travis script on this. It will not take much time!
