### ISSUE TITLE
Add setting options for feature requests/bugs

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#120]

**Comment by dhamanutd** [comment]
@jorgegil96 can you explain me more about this? is it like create a report form? Maybe i can help work this issue

**Comment by jorgegil96** [comment]
I was thinking of adding an "About" section at the bottom of the settings screen (below "Reddit") with the version number and a "Report bug or suggest a feature" item that opens un a dialog with a textbox with a send button
