### ISSUE TITLE
Update token on startup

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#13]

**Comment by djKooks** [comment]
Hello~I'm also a fan of NBA, and interested on your app. 
When I open app overtime, I see toast `Authenticated` every time. Is this related with this issue?

**Comment by jorgegil96** [comment]
Hey,
So the app is actually in a complicated/messy state right now with some features being half done or incorrectly implemented. I just recently started trying to get everything in order by adding milestones for the next release and working on a specific set of features instead of trying to make everything work at once.

Anyway, I don't if you're familiar with how reddit authentication works and the [JRAW](https://github.com/thatJavaNerd/JRAW) library that I'm using but basically there's two kinds of authentication, **userless** and **with credentials**.
The current implementation does **userless** on start up, this means that we authenticate but the user is not logged in (so he can't comment or upvote etc...). This is why you see a Toast everytime you start the app.
There is also a not finished implementation of the **with credentials** authentication. This is started when you go to *profile* and log in with your Reddit account.

This issue is for the **with credentials** authentication. A token is saved when you log in with Reddit but if you close and reopen the app you need to log in again because I'm not doing anything with the saved token right now. The app should try to update the token on start up so that the user doesn't have to log in again.

I have decided to leave **with credentials** authentication out of the first release because I think other more fundamentals features should be worked on first, but you can work on it if you want.

**Comment by djKooks** [comment]
Okay, I got it. How about store your log in information data as Android preference and use it every time when it needs to log in? Surely, you need to input data again when it is removed.

**Comment by jorgegil96** [comment]
Yeah, that's the idea, use the saved information from when they logged in and try to authenticate when the app starts.
What do you mean log in information though? We cannot save username and password, we don't have access to that. We only have access to the token.
If you check out [this line](https://github.com/jorgegil96/All-NBA/blob/master/app/src/main/java/com/example/jorgegil/closegamealert/View/Activities/LoginActivity.java#L106), I have already saved the token in shared preferences. What you need to do on startup is use that saved token to get a new valid one, you can use [OAuthHelper.setRefreshToken(String)](http://thatjavanerd.github.io/JRAW/docs/0.7.0.2/net/dean/jraw/http/oauth/OAuthHelper.html#setRefreshToken(java.lang.String)) followed by [OAuthHelper.refreshToken(Credentials)](https://thatjavanerd.github.io/JRAW/docs/0.7.0.2/net/dean/jraw/http/oauth/OAuthHelper.html#refreshToken(net.dean.jraw.http.oauth.Credentials)) to retrieve another valid access token, where String=saved token and Credentials is [this](https://github.com/jorgegil96/All-NBA/blob/master/app/src/main/java/com/example/jorgegil/closegamealert/View/Activities/LoginActivity.java#L42).

This logic would go inside [this method](https://github.com/jorgegil96/All-NBA/blob/master/app/src/main/java/com/example/jorgegil/closegamealert/Utils/RedditAuthentication.java#L34), before starting the current UserlessAuthTask you check if there is a token saved, if there is one then you try to authenticate with it, if there isn't, then you do the UserlessAuthTask.

**Comment by djKooks** [comment]
Oh, I got it. Thanks.
