### ISSUE TITLE
Load all comments of a submission

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#133]

**Comment by knightcube** [comment]
what is a submission here? is it a basketball term or a feature of the app?

**Comment by jorgegil96** [comment]
A `Submission` is a reddit thread, [like this one](https://www.reddit.com/r/nba/comments/784gt7/carmelo_puts_okc_up_by_1_before_wiggins_wins_it/)  

The issue here is that when you fetch a submission, not all comments are included in the response, some `CommentNode`s will sometimes say they have more children, but they aren't really loaded in the response. This is why you'll sometimes see a text under some comments that says "Load more comments" (both in reddit.com and in the app). I know there are more comments to load, so I should do that when they click "Load more comments".  

See https://github.com/jorgegil96/All-NBA/blob/master/app/src/main/java/com/gmail/jorgegilcavazos/ballislife/features/common/ThreadAdapter.java#L275  
And https://github.com/mattbdean/JRAW
