### ISSUE TITLE
Sort teams in standings

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#147]

**Comment by knightcube** [comment]
Do you want it be sorted alphabetically?

**Comment by jorgegil96** [comment]
No, it should be sorted by the "seed" attr of TeamStanding. It's almost always already sorted when you get the data but it's not really a guarantee.  

So you'd need to sort the each list of TeamStandings(east and west) in Standings by seed (from 1 to 15).  

Here's the data source if you're wondering what it look like. https://nba-app-ca681.firebaseio.com/standings/22016.json?print=pretty

**Comment by jorgegil96** [comment]
@cmspray join the Gitter chat if you'd like to keep up to date on the project's progress
