### ISSUE TITLE
Highlight OP's and logged-in user's comments

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#179]
OP - blue
Me - yellow

**Comment by naishadhparmar** [comment]
Is this issue closed? I am a beginner and if somebody can give me some pointers, I can do this.

**Comment by jorgegil96** [comment]
Yes, this has has been close already, it appears as open because the `develop` branch where it was made hasn't been merged to `master.  

If you join the [Gitter chat](https://gitter.im/All-NBA-Android) I can give you access to a roadmap of what issues are pending and give you pointers on how to contribute.

**Comment by naishadhparmar** [comment]
@jorgegil96 I have joine the Gitter chat.
