### ISSUE TITLE
Create spash screen

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#19]

**Comment by djKooks** [comment]
Okay~I'll follow up here

**Comment by jorgegil96** [comment]
Whoops. Fixed.

**Comment by djKooks** [comment]
Got it~

**Comment by djKooks** [comment]
How do you think about making UserlessAuthTask class as public and put authenticate logic on Splashscreen?

**Comment by jorgegil96** [comment]
@djKooks I would suggest we keep that subclass private and you can add a public method that runs the task (similar to updateToken() ) to the RedditAuthentication class so that you can authenticate form the splashscreen.

**Comment by djKooks** [comment]
@jorgegil96 Okay~

**Comment by jorgegil96** [comment]
@djKooks Nice work! We'll probably need to change the image in the future when the app name/color palette is decided on but that's just a resource change.
