### ISSUE TITLE
In SubmissionWrapper, the call to get high res thumbnail url can throw NPE

### ISSUE THREAD

**Issue by vishnumad** [jorgegil96/All-NBA#231]
Specifically it's happening for [this post](https://www.reddit.com/r/timberwolves/comments/9l66md/josh_okogie_didnt_know_honey_bbq_sauce_was/) which contains an embedded Reddit video. 

`2018-10-03 18:45:33.528 18530-18530/com.gmail.jorgegilcavazos.ballislife.debug E/PostsPresenter: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fasterxml.jackson.databind.JsonNode.has(java.lang.String)' on a null object reference`

JRAW assumes that a submission has an "oembed" field when there is a "media" field in the submission. The fix is to not use the Submission's `getOEmbedMedia()` method in the SubmissionWrapper and get the object yourself from the dataNode.

**Comment by jorgegil96** [comment]
Some context: https://github.com/mattbdean/JRAW/issues/198

Thanks vishnumad!
