### ISSUE TITLE
Add a Streak column in the standings

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#234]

**Comment by herou** [comment]
![Screenshot_20190606-124121_Swish](https://user-images.githubusercontent.com/13895430/59027143-84525a80-8858-11e9-8678-8f1558df8ff9.jpg)

Have you already added it? I see the STRK column.

**Comment by jorgegil96** [comment]
Hi Herou, yes I have, looks like I forgot to close it
