### ISSUE TITLE
New app name

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#28]
The goal is to publish the app on the Play Store, unfortunately, I'm pretty sure it'll be rejected if I use "NBA" in its name, so a new name for the app is needed.

Any suggestions are appreciated.

**Comment by djKooks** [comment]
Well, 'ball in life' seems not bad, but more important thing looks like that you need to think about making the strong part on your app comparing with official NBA application. Do you have some kind of concept, or roadmap?
It seems connecting with reddit is one good idea.

**Comment by jorgegil96** [comment]
I don't really have a concrete roadmap.  
I'd say the main features that I want on the app are:  
* Live scores with boxscores  
* Comment threads for each game  
* Alerts when a game is getting exciting (but this is mostly done on the server side)  
* Reddit posts (layout similar to other Reddit app like "Sync")  
* Highlights from reddit or streamable  
* All reddit comment threads for games and posts should have basic features such as commenting and upvoting

**Comment by djKooks** [comment]
@jorgegil96 Thanks. For now, it seems quite enough. Let's keep think about it.

**Comment by jorgegil96** [comment]
Yeah no problem, feel free to suggest new features or changes to existing ones.
Hmmm, yes, emphasizing the *discussion* aspect of the app could be good. If you have specific suggestions post them, anything is welcomed. I'd suggest keeping it short/catchy though.
