### ISSUE TITLE
Update launcher icon

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#6]
Current one is ugly

**Comment by djKooks** [comment]
How about adding splash screen too?

**Comment by jorgegil96** [comment]
Would be nice too. Wanna work on that?

**Comment by djKooks** [comment]
Fine~could you prepare full-size image for intro?

**Comment by jorgegil96** [comment]
Yeah, I'll add one for testing later. Let's move this conversation to [#19](https://github.com/jorgegil96/All-NBA/issues/19).

**Comment by jorgegil96** [comment]
Basketball in icon should be white
