### ISSUE TITLE
Home and Away discrepancy 

### ISSUE THREAD

**Issue by nischaltamang** [jorgegil96/All-NBA#61]
In the Games section, the order of the home and away team is in the wrong order. Typically if the teams are listed in a horizontal layout, Away is on the left and Home is on the right. 

http://www.nba.com/
http://www.espn.com/nba/boxscore?gameId=400900222

**Comment by jorgegil96** [comment]
You're right, I'll get this fixed with the next Game section UI update that was coming anyway.

Thanks for letting me know!

**Comment by jorgegil96** [comment]
Awesome, thanks man!
